version: '3.8'

services:
  book-service:
    build:
      context: ./services/book-service
    ports:
      - "5001:5001"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    networks:
      - platform-network

  review-service:
    build:
      context: ./services/review-service
    ports:
      - "5002:5002"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    networks:
      - platform-network

  frontend-service:
    build:
      context: ./services/frontend-service
    ports:
      - "8080:5000"
    environment:
      - BOOK_SERVICE_URL=http://book-service:5001
      - REVIEW_SERVICE_URL=http://review-service:5002
    networks:
      - platform-network
    depends_on:
      - book-service
      - review-service

networks:
  platform-network:
    driver: bridge
