replicaCount: 1
image:
  repository: omershuker/book-service
  tag: dev-1fad2ead97ce2464d351e9ae362ec6d7adc635ae # Automated by GitHub Actions for dev, or prod-latest for prod
service:
  type: ClusterIP
  port: 5001
  targetPort: 5001
