replicaCount: 1
image:
  repository: omershuker/frontend-service
  tag: prod-latest
service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30180 # Accessible outside AWS at http://<EC2-IP>:30080
env:
  - name: BOOK_SERVICE_URL
    value: "http://book-service:5001"
  - name: REVIEW_SERVICE_URL
    value: "http://review-service:5002"