replicaCount: 1
image:
  repository: omershuker/review-service
  tag: dev-1fad2ead97ce2464d351e9ae362ec6d7adc635ae # Automated by GitHub Actions for dev, or prod-latest for prod
service:
  type: ClusterIP
  port: 5002
  targetPort: 5002
